### ISSUE TITLE
Questions about the TGV in the paper?

### ISSUE THREAD

**Issue by llcc343** [PolarNick239/OOCSurfaceReconstructionPaper#2]
Hi, in your paper you mentioned that the numeric fusion scheme like the 2.5D TGV-Fusion, but as far as I known that the TV-Hist you used introduced by Zack is essentially an TV-L1 TSDF denoising algorithm. I felt very confused that how do you handle the dual formulation of the fused data term of the TSDF.

**Comment by PolarNick239** [comment]
Hi,

yes, I started with TV-L1 TSDF formulation from C. Zach. But I wanted to regularize surface normals too. TGV-Fusion was a paper that helped me to do so (see fig. 14 in TGV-Fusion). While its formulation operates on 2D regular grid - you just need to adapt it to 3D regular grid (f.e. just use 3D divergence operator) and you will add surface normals regularization into Zach approach.

**Comment by llcc343** [comment]
Thanks for your kind reply. Formula 14 in TGV-fusion should be used in the multiple observations case in the data-term, so we can calculate the dual transformation(ie r_h_l). For the TV-Hist or TGV-Hist case the dual transformation of the data term should be equal to a generalized shrinkage (see the paper "Online 3D reconstruction using Convex Optimization"). So the update of dual variable r_h_l is not need? That is where I felt confused when I read the derivation in your paper. 
 
I am also doing some tests using the TGV-Fusion formula on multiple frame tsdf volumes. It seems that the fusion results are really bad. It seems that the a tsdf volume from a single frame can not cover the whole scene which cause the update of the dual field u do not converge well.

**Comment by PolarNick239** [comment]
I also noted some anomalies in fig. 14 in TGV-Fusion [1]. That was about odd **independence** between pairs **p+u** and **v+q**. For me it was helpful to search for these formulas in similar papers, and these two papers contain the same formula but without mistakes - [FUSION OF MULTI-RESOLUTION DIGITAL SURFACE MODELS](https://www.int-arch-photogramm-remote-sens-spatial-inf-sci.net/XL-1-W3/247/2013/isprsarchives-XL-1-W3-247-2013.pdf) [2] - see Fig. 9, and [Spatially Regularized Fusion of Multi-Resolution Digital Surface Models](https://core.ac.uk/download/pdf/147323907.pdf) [3] - see Listing 1:

![image](https://user-images.githubusercontent.com/1218605/196469369-536c2007-f1f9-439e-8470-878ff6aff4f6.png)
